# https://blog.benoitblanchon.fr/github-action-run-ssh-commands/
name: CI
on: [push]
jobs:
  deploy:
    name: 'Droplet Deploy'
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/droplet.key
          chmod 600 ~/.ssh/droplet.key
          cat >>~/.ssh/config <<END
          Host droplet
            HostName $SSH_HOST
            User root
            IdentityFile ~/.ssh/droplet.key
            StrictHostKeyChecking no
          END
        env:
          SSH_KEY: ${{ secrets.SSHKEY }}
          SSH_HOST: ${{ secrets.HOST }}

      - name: print root
        run: ssh droplet 'whoami'

      - name: update repo
        run: ssh droplet 'cd /repos/beachStats/ && git pull && npm install'

      - name: build repo
        run: ssh droplet 'cd /repos/beachStats/ && npm run build'

      - name: copy .env
        run: ssh droplet 'cd /repos/beachStats/ && cp /repos/beachStats/.env /repos/beachStats/build/'

      - name: update process
        run: ssh droplet 'source ~/.nvm/nvm.sh && pm2 list && pm2 start /repos/beachstats/build/app.js --name beachstats && pm2 reload beachstats --update-env'

      - name: check server running
        run: ssh droplet 'curl 127.0.0.1:3100'
