# https://github.com/appleboy/ssh-action#setting-up-ssh-key
name: Deploy
on: [push]
jobs:
  push-to-vps:
    runs-on: ubuntu-latest
    steps:
      - name: execute
        uses: appleboy/ssh-action@dce9d56
        with:
          HOST: ${{ secrets.HOST }}
          USERNAME: root
          PORT: 22
          KEY: ${{ secrets.SSHKEY }}
          script: |
            whoami
            ls -al
