name: Deploy
on: [push]
jobs:
  push-to-vps:
    runs-on: ubuntu-latest
    steps:
      - name: execute
        uses: appleboy/ssh-action@master
        with:
          HOST: ${{ secrets.HOST }}
          USERNAME: root
          PORT: 22
          KEY: ${{ secrets.SSHKEY }}
          script_stop: true # stops on script failure
          script: |
            whoami
            ls -al
